### ISSUE TITLE
Working with Nextflow Workflows

### ISSUE THREAD

**Issue by erinyoung** [CDCgov/mycosnp#15]
This isn't a bug per se, and this may not even be intended for the creators of this workflow. 

Many public health laboratories use nextflow for their workflows. The State Public Health Bioinformaticians (StaPh-B) maintain a toolkit with many of these nextflow workflows (https://github.com/StaPH-B/staphb_toolkit). If mycosnp is going to be utilized widely by the state public health labs, it would be awesome if this workflow could be connected as a process or something to a nextflow workflow (aka "nextflowized").

Has anyone attempted anything like that?

I would like to add mycosnp to that staphB toolkit and my lab's nextflow workflow. I've created processes with snakemake workflows (i.e. pangolin), but it doesn't look the commands are readily amenable to that idea.

**Comment by mciprianoCDC** [comment]
https://github.com/CDCgov/mycosnp-nf
